<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<UseWindowsForms>true</UseWindowsForms>
		<TargetFramework>net9.0-windows</TargetFramework>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Enrichers.Environment" />
		<PackageReference Include="Serilog.Enrichers.Process" />
		<PackageReference Include="Serilog.Enrichers.Thread" />
		<PackageReference Include="Serilog.Extensions.Hosting" />
		<PackageReference Include="Serilog.Settings.Configuration" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Analogy.LogViewer.Serilog.Sinks\Analogy.LogViewer.Serilog.Sinks.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" />
	</ItemGroup>

</Project>