<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net9.0-windows;net8.0-windows;net48</TargetFrameworks>
	  <Copyright>Lior Banai 2022-2025</Copyright>
	  <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="IAnalogy\**" />
    <EmbeddedResource Remove="IAnalogy\**" />
    <None Remove="IAnalogy\**" />
  </ItemGroup>


	<ItemGroup>
		<PackageReference Include="Analogy.CommonUtilities" />
		<PackageReference Include="Analogy.LogViewer.Interfaces" />
		<PackageReference Include="Analogy.LogViewer.Template" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="System.Resources.Extensions" />
	</ItemGroup>


	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" />
	</ItemGroup>
</Project>
