//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analogy.LogViewer.Serilog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analogy.LogViewer.Serilog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogySerilog {
            get {
                object obj = ResourceManager.GetObject("AnalogySerilog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogySerilog16x16 {
            get {
                object obj = ResourceManager.GetObject("AnalogySerilog16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogySerilog32x32 {
            get {
                object obj = ResourceManager.GetObject("AnalogySerilog32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;@t&quot;: &quot;2019-12-10T13:33:23.0970926Z&quot;,
        ///    &quot;@mt&quot;: &quot;An unknown error occurred&quot;,
        ///    &quot;@l&quot;: &quot;Error&quot;,
        ///    &quot;@x&quot;: &quot;Exception stack trace&quot;,
        ///    &quot;SourceContext&quot;: &quot;MySourceContext&quot;,
        ///    &quot;Scope&quot;: [
        ///      &quot;FirstScope&quot;,
        ///      1850562557,
        ///      &quot;198441851&quot;
        ///    ],
        ///    &quot;MachineName&quot;: &quot;MY-MACHINE&quot;,
        ///    &quot;EnvironmentUserName&quot;: &quot;WORKGROUP\\SYSTEM&quot;,
        ///    &quot;ExceptionDetail&quot;: {
        ///      &quot;HResult&quot;: -2146233087,
        ///      &quot;Message&quot;: &quot;Internal Error&quot;,
        ///      &quot;Source&quot;: &quot;System.ServiceModel&quot;,
        ///      &quot;Action&quot;: null,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompactJsonFormatPerFile {
            get {
                return ResourceManager.GetString("CompactJsonFormatPerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@t&quot;:&quot;2016-10-12T04:46:58.0554314Z&quot;,&quot;@mt&quot;:&quot;Hello, {@User}&quot;,&quot;User&quot;:{&quot;Name&quot;:&quot;nblumhardt&quot;,&quot;Id&quot;:101}}
        ///{&quot;@t&quot;:&quot;2016-10-12T04:46:58.0684369Z&quot;,&quot;@mt&quot;:&quot;Number {N:x8}&quot;,&quot;@r&quot;:[&quot;0000002a&quot;],&quot;N&quot;:42}
        ///{&quot;@t&quot;:&quot;2016-10-12T04:46:58.0724384Z&quot;,&quot;@mt&quot;:&quot;Tags are {Tags}&quot;,&quot;@l&quot;:&quot;Warning&quot;,&quot;Tags&quot;:[&quot;test&quot;,&quot;orange&quot;]}
        ///{&quot;@t&quot;:&quot;2016-10-12T04:46:58.0904378Z&quot;,&quot;@mt&quot;:&quot;Something failed&quot;,&quot;@l&quot;:&quot;Error&quot;, &quot;@x&quot;:&quot;System.DivideByZer...&lt;snip&gt;&quot;}.
        /// </summary>
        internal static string CompactJsonFormatPerLine {
            get {
                return ResourceManager.GetString("CompactJsonFormatPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Timestamp&quot;: &quot;2020-06-07T13:44:57.8532799+10:00&quot;,
        ///    &quot;Level&quot;: &quot;Information&quot;,
        ///    &quot;MessageTemplate&quot;: &quot;Hello, {@User}, {N:x8} at {Now}&quot;,
        ///    &quot;Properties&quot;: {
        ///      &quot;User&quot;: {
        ///        &quot;Name&quot;: &quot;nblumhardt&quot;,
        ///        &quot;Tags&quot;: [ 1, 2, 3 ]
        ///      },
        ///      &quot;N&quot;: 123,
        ///      &quot;Now&quot;: &quot;2016-06-07T13:44:57.8532799+10:00&quot;
        ///    },
        ///    &quot;Renderings&quot;: {
        ///      &quot;N&quot;: [
        ///        {
        ///          &quot;Format&quot;: &quot;x8&quot;,
        ///          &quot;Rendering&quot;: &quot;0000007b&quot;
        ///        }
        ///      ]
        ///    }
        ///  },
        ///  {
        ///    &quot;Timestamp&quot;: &quot;2016-06-07T13: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonFormatFile {
            get {
                return ResourceManager.GetString("JsonFormatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Timestamp&quot;:&quot;2020-06-07T13:44:57.8532799+10:00&quot;,&quot;Level&quot;:&quot;Information&quot;,&quot;MessageTemplate&quot;:&quot;Hello, {@User}, {N:x8} at {Now}&quot;,&quot;Properties&quot;:{&quot;User&quot;:{&quot;Name&quot;:&quot;nblumhardt&quot;,&quot;Tags&quot;:[1,2,3]},&quot;N&quot;:123,&quot;Now&quot;:&quot;2016-06-07T13:44:57.8532799+10:00&quot;},&quot;Renderings&quot;:{&quot;N&quot;:[{&quot;Format&quot;:&quot;x8&quot;,&quot;Rendering&quot;:&quot;0000007b&quot;}]}}
        ///{&quot;Timestamp&quot;:&quot;2016-06-07T13:44:57.8532799+10:00&quot;,&quot;Level&quot;:&quot;Information&quot;,&quot;MessageTemplate&quot;:&quot;Hello, {@User}, {N:x8} at {Now}&quot;,&quot;Properties&quot;:{&quot;User&quot;:{&quot;Name&quot;:&quot;Lior&quot;,&quot;Tags&quot;:[1,2,3]},&quot;N&quot;:123,&quot;Now&quot;:&quot;2016-06-07T13:44:57.8532799+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonFormatPerLine {
            get {
                return ResourceManager.GetString("JsonFormatPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Serilog_icon {
            get {
                object obj = ResourceManager.GetObject("Serilog_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Serilog_icon32x32 {
            get {
                object obj = ResourceManager.GetObject("Serilog_icon32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
