//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analogy.LogViewer.Serilog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analogy.LogViewer.Serilog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogySerilog {
            get {
                object obj = ResourceManager.GetObject("AnalogySerilog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogySerilog16x16 {
            get {
                object obj = ResourceManager.GetObject("AnalogySerilog16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnalogySerilog32x32 {
            get {
                object obj = ResourceManager.GetObject("AnalogySerilog32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CompactJsonFormatPerFile {
            get {
                return ResourceManager.GetString("CompactJsonFormatPerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;@t&quot;:&quot;2016-10-12T04:46:58.0554314Z&quot;,&quot;@mt&quot;:&quot;Hello, {@User}&quot;,&quot;User&quot;:{&quot;Name&quot;:&quot;nblumhardt&quot;,&quot;Id&quot;:101}}
        ///{&quot;@t&quot;:&quot;2016-10-12T04:46:58.0684369Z&quot;,&quot;@mt&quot;:&quot;Number {N:x8}&quot;,&quot;@r&quot;:[&quot;0000002a&quot;],&quot;N&quot;:42}
        ///{&quot;@t&quot;:&quot;2016-10-12T04:46:58.0724384Z&quot;,&quot;@mt&quot;:&quot;Tags are {Tags}&quot;,&quot;@l&quot;:&quot;Warning&quot;,&quot;Tags&quot;:[&quot;test&quot;,&quot;orange&quot;]}
        ///{&quot;@t&quot;:&quot;2016-10-12T04:46:58.0904378Z&quot;,&quot;@mt&quot;:&quot;Something failed&quot;,&quot;@l&quot;:&quot;Error&quot;, &quot;@x&quot;:&quot;System.DivideByZer...&lt;snip&gt;&quot;}.
        /// </summary>
        internal static string CompactJsonFormatPerLine {
            get {
                return ResourceManager.GetString("CompactJsonFormatPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JsonFormatFile {
            get {
                return ResourceManager.GetString("JsonFormatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JsonFormatPerLine {
            get {
                return ResourceManager.GetString("JsonFormatPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Serilog_icon {
            get {
                object obj = ResourceManager.GetObject("Serilog_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Serilog_icon32x32 {
            get {
                object obj = ResourceManager.GetObject("Serilog_icon32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
